version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.5
       - image: circleci/postgres:9.5
     steps:
       - checkout
       - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install codecov
            pip install -r requirements.txt -r requirements-dev.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test
            codecov